"""Add description to groups and tags

Revision ID: 26e4ba4c4e6e
Revises: cc05b887dd03
Create Date: 2026-01-20 13:30:43.212095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26e4ba4c4e6e"
down_revision: Union[str, Sequence[str], None] = "cc05b887dd03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("primary_groups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("primary_groups", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
