"""Add provider and is_available to ExchangeRateHistory

Revision ID: 7944ce74a3a1
Revises: 85e47112a465
Create Date: 2026-01-18 08:17:01.145867

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7944ce74a3a1"
down_revision: Union[str, Sequence[str], None] = "85e47112a465"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
