"""Add check constraints to transactions

Revision ID: 85e47112a465
Revises: f7c95f33281c
Create Date: 2026-01-18 08:08:37.685414

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "85e47112a465"
down_revision: Union[str, Sequence[str], None] = "f7c95f33281c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
