"""Add SystemSetting model

Revision ID: a722d1f9ef1d
Revises: 26e4ba4c4e6e
Create Date: 2026-01-20 20:04:34.532753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a722d1f9ef1d'
down_revision: Union[str, Sequence[str], None] = '26e4ba4c4e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    op.drop_table('system_settings')
    # ### end Alembic commands ###
