"""Final check before v1.3.0 release

Revision ID: cc05b887dd03
Revises: e7d98f0edfbe
Create Date: 2026-01-19 19:29:49.718244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc05b887dd03"
down_revision: Union[str, Sequence[str], None] = "e7d98f0edfbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("asset_types", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_types_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("custodians", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_custodians_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("primary_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_primary_groups_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("(TRUE)"),
        )
        batch_op.alter_column(
            "is_verified",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("(FALSE)"),
        )
        batch_op.alter_column(
            "email_verified",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("(FALSE)"),
        )
        batch_op.alter_column(
            "is_admin",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("(FALSE)"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_admin",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("(FALSE)"),
        )
        batch_op.alter_column(
            "email_verified",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("(FALSE)"),
        )
        batch_op.alter_column(
            "is_verified",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("(FALSE)"),
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("(TRUE)"),
        )

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_user_id"))

    with op.batch_alter_table("primary_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_primary_groups_user_id"))

    with op.batch_alter_table("custodians", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_custodians_user_id"))

    with op.batch_alter_table("asset_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_types_user_id"))

    # ### end Alembic commands ###
