"""Add composite indexes

Revision ID: d85b864326bb
Revises: 7944ce74a3a1
Create Date: 2026-01-18 08:20:16.599117

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d85b864326bb"
down_revision: Union[str, Sequence[str], None] = "7944ce74a3a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exchange_rate_history", schema=None) as batch_op:
        batch_op.create_index(
            "idx_currency_timestamp", ["currency", "timestamp"], unique=False
        )

    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.create_index(
            "idx_asset_date_source", ["asset_id", "date", "source"], unique=False
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index("idx_asset_date", ["asset_id", "date"], unique=False)
        batch_op.create_index("idx_date_type", ["date", "type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("idx_date_type")
        batch_op.drop_index("idx_asset_date")

    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.drop_index("idx_asset_date_source")

    with op.batch_alter_table("exchange_rate_history", schema=None) as batch_op:
        batch_op.drop_index("idx_currency_timestamp")

    # ### end Alembic commands ###
