"""Add system agents

Revision ID: eae6bf3d0c23
Revises: a722d1f9ef1d
Create Date: 2026-01-21 08:47:25.380039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae6bf3d0c23'
down_revision: Union[str, Sequence[str], None] = 'a722d1f9ef1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_duration_ms', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=True),
    sa.Column('schedule_value', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('agent_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_agents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_agents_name'), ['name'], unique=True)

    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['system_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agent_logs_level'))
        batch_op.drop_index(batch_op.f('ix_agent_logs_id'))

    op.drop_table('agent_logs')
    with op.batch_alter_table('system_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_agents_name'))
        batch_op.drop_index(batch_op.f('ix_system_agents_id'))

    op.drop_table('system_agents')
    # ### end Alembic commands ###
