"""Convert Float to Decimal for financial fields

Revision ID: f7c95f33281c
Revises: d4a79170cf32
Create Date: 2026-01-18 07:32:48.458410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7c95f33281c"
down_revision: Union[str, Sequence[str], None] = "d4a79170cf32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Get connection and inspector to check table existence
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # Only alter tables that exist
    if "assets" in existing_tables:
        with op.batch_alter_table("assets", schema=None) as batch_op:
            batch_op.alter_column(
                "quantity",
                existing_type=sa.FLOAT(),
                type_=sa.Numeric(precision=20, scale=8),
                existing_nullable=True,
            )
            batch_op.alter_column(
                "purchase_price",
                existing_type=sa.FLOAT(),
                type_=sa.Numeric(precision=20, scale=8),
                existing_nullable=True,
            )

    if "exchange_rate_history" in existing_tables:
        with op.batch_alter_table("exchange_rate_history", schema=None) as batch_op:
            batch_op.alter_column(
                "rate",
                existing_type=sa.FLOAT(),
                type_=sa.Numeric(precision=20, scale=8),
                existing_nullable=True,
            )
    else:
        # Create the table if it doesn't exist
        op.create_table(
            "exchange_rate_history",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("currency", sa.String(), nullable=False, index=True),
            sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
            sa.Column("timestamp", sa.DateTime(), nullable=False, index=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("currency", "timestamp", name="uq_currency_timestamp"),
        )
        # Create indexes only if they don't exist
        existing_indexes = [
            idx["name"] for idx in inspector.get_indexes("exchange_rate_history")
        ]
        if "ix_exchange_rate_history_currency" not in existing_indexes:
            op.create_index(
                op.f("ix_exchange_rate_history_currency"),
                "exchange_rate_history",
                ["currency"],
                unique=False,
            )
        if "ix_exchange_rate_history_timestamp" not in existing_indexes:
            op.create_index(
                op.f("ix_exchange_rate_history_timestamp"),
                "exchange_rate_history",
                ["timestamp"],
                unique=False,
            )

    if "price_history" in existing_tables:
        with op.batch_alter_table("price_history", schema=None) as batch_op:
            batch_op.alter_column(
                "price",
                existing_type=sa.FLOAT(),
                type_=sa.Numeric(precision=20, scale=8),
                existing_nullable=True,
            )

    if "transactions" in existing_tables:
        with op.batch_alter_table("transactions", schema=None) as batch_op:
            batch_op.alter_column(
                "quantity_change",
                existing_type=sa.FLOAT(),
                type_=sa.Numeric(precision=20, scale=8),
                existing_nullable=True,
            )
            batch_op.alter_column(
                "price_per_unit",
                existing_type=sa.FLOAT(),
                type_=sa.Numeric(precision=20, scale=8),
                existing_nullable=True,
            )
            batch_op.alter_column(
                "fees",
                existing_type=sa.FLOAT(),
                type_=sa.Numeric(precision=20, scale=8),
                existing_nullable=True,
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.alter_column(
            "fees",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "price_per_unit",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "quantity_change",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("exchange_rate_history", schema=None) as batch_op:
        batch_op.alter_column(
            "rate",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.alter_column(
            "purchase_price",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "quantity",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
